spring:
  r2dbc:
    password: admin
    username: admin
    url: r2dbc:h2:mem:///customers
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

  rsocket:
    server:
      port: 7000